# Generated by Django 3.2.4 on 2021-06-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('Student_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_register.grade')),
            ],
        ),
    ]
